version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=900
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
    ports:
      - "3000:3000"